### ISSUE TITLE
모든 황혼전: 시련 그마 정보 확인 기능 추가

### ISSUE THREAD

**Issue by krepe-suZette** [unitymind9/d2reset-issues#17]
시즌 말 황혼전: 시련 그랜드마스터 6종에 모두 접근 가능할 때 해당하는 모든 그랜드마스터 황혼전에 대한 정보 (용사 종류 등)를 확인할 수 있었으면 좋겠음.

**Comment by unitymind9** [comment]
현재 작업 중에 있으며 시즌 종료 전까지 꼭 반영하도록 하겠습니다

**Comment by unitymind9** [comment]
결과:
![image](https://user-images.githubusercontent.com/61493917/116447551-13c0e680-a893-11eb-8b1e-11ac0801abe1.png)
모디파이어 추가는 고려해보겠습니다
