### ISSUE TITLE
각 황혼전 실드 속성 및 실드몹 수

### ISSUE THREAD

**Issue by BrokenHead44078** [unitymind9/d2reset-issues#4]
를 추가해주면 좋을 거 같다

**Comment by unitymind9** [comment]
실드 속성: 황시 페이지에서 확인할 수 잇읍니다
![image](https://user-images.githubusercontent.com/61493917/103355983-0a955800-4af3-11eb-83f5-9d1bc57a7965.png)
요렇게

실드몹 수: 추가해보겠읍니다

**Comment by BrokenHead44078** [comment]
> 실드 속성: 황시 페이지에서 확인할 수 잇읍니다
> ![image](https://user-images.githubusercontent.com/61493917/103355983-0a955800-4af3-11eb-83f5-9d1bc57a7965.png)
> 요렇게
> 
> 실드몹 수: 추가해보겠읍니다

고맙다

**Comment by BrokenHead44078** [comment]
> 실드 속성: 황시 페이지에서 확인할 수 잇읍니다
> ![image](https://user-images.githubusercontent.com/61493917/103355983-0a955800-4af3-11eb-83f5-9d1bc57a7965.png)
> 요렇게
> 
> 실드몹 수: 추가해보겠읍니다

https://d2-info.web.app/milestone 

여기도 비슷한건데 내가 말한게 이런거

**Comment by unitymind9** [comment]
노력해보겟읍니다

**Comment by unitymind9** [comment]
결과
![image](https://user-images.githubusercontent.com/61493917/103414983-8fe83d80-4bc3-11eb-8597-aebaa2a4e58b.png)
![image](https://user-images.githubusercontent.com/61493917/103414987-9676b500-4bc3-11eb-9931-c841c8c8520b.png)
