### ISSUE TITLE
에버버스 목록 추가

### ISSUE THREAD

**Issue by sungbai01** [unitymind9/d2reset-issues#6]
에버버스가 판매하는 주간 아이템 목록과 일일할인하는 아이템이 뭔지도 나왔으면 좋겠음

**Comment by unitymind9** [comment]
제가 할수있는 범위 내인지 확인해보겟읍니다

**Comment by unitymind9** [comment]
임시 적용
![image](https://user-images.githubusercontent.com/61493917/103409527-a209b200-4baa-11eb-9ae8-b25a3110b871.png)

문제점:
워록 아이템만 보임. 아마 상인 방어구 문제를 해결할 때 까지는 해결할 수 없을 것 같습니다.

**Comment by unitymind9** [comment]
상인 방어구를 마무리한 후 진행예정입니다

**Comment by unitymind9** [comment]
중간결과:
![image](https://user-images.githubusercontent.com/61493917/103439566-62fa6000-4c81-11eb-8d66-feb267533bca.png)

보완해야할 점:
워록 아이템을 전부 출력한 이후 타이탄, 헌터 캐릭터가 구매할 수 있는 아이템이 보이는 형식이라 좀 이쁘지가 않음
광휘가루 가격 추가

**Comment by unitymind9** [comment]
결과:
![image](https://user-images.githubusercontent.com/61493917/103461744-f6a45d00-4d63-11eb-951c-e15da083ddbf.png)
